import React from "react";
import ClerkProviderClient from "@/components/ClerkProviderClient";
import { Montserrat } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ecommerce App for Shoppers",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const hasClerkKey = !!process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

  const content = (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        {children}
      </body>
    </html>
  );

  return hasClerkKey ? (
    <ClerkProviderClient>{content}</ClerkProviderClient>
  ) : (
    content
  );
};

export default RootLayout;
